### ISSUE TITLE
Operations Complexity

### ISSUE THREAD

**Issue by miskolc** [DanielStutzbach/heapdict#10]
What are the complexities for the operations performed on the HeapDict? I'm particulary interested on assigning new values. Does it take O(logN) operations to make the heap stable again( with the minimum at as root)?

**Comment by DanielStutzbach** [comment]
HeapDict's heap implementation is an ordinary binary heap.  The time complexities are shown here:
https://en.wikipedia.org/wiki/Heap_(data_structure)#Comparison_of_theoretic_bounds_for_variants
