### ISSUE TITLE
heapdict should do a stable sort

### ISSUE THREAD

**Issue by andreasvc** [DanielStutzbach/heapdict#4]
When items with the same priority are inserted, they are not popped in the order that they were inserted. The order seems to be the reverse (LIFO instead of FIFO). Python's heapq and sorted do maintain stable sort. In terms of priorities it makes sense that for all items with the same priority, the one that has been waiting the longest should go first.

I tried changing some things in the code to see if it could easily be fixed (the len(heap) part of the wrappers seemed related), but unfortunately there are no comments.

**Comment by acrenshaw94** [comment]
Learned a lot from this article: https://docs.python.org/3/library/heapq.html#priority-queue-implementation-notes
